project_id = "pksyokumflsyvjcmtjmv"

[auth.email.template.confirmation]
subject = "Confirm your email"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.invite]
subject = "You've been invited to a household"
content_path = "./supabase/templates/invite.html"

[auth.email.template.magic_link]
subject = "Your login link"
content_path = "./supabase/templates/magic_link.html"

[auth.email.template.email_change]
subject = "Confirm your new email"
content_path = "./supabase/templates/email_change.html"

[auth.email.template.recovery]
subject = "Reset your password"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.reauthentication]
subject = "Your verification code"
content_path = "./supabase/templates/reauthentication.html"
